const SAMPLE_LESSONS = [
  {
    id: 'sample-1',
    subject: 'Science',
    topic: 'Planets in the Solar System',
    gradeLevel: 'Grade 2',
    grade: 2,
    duration: 45,
    quarter: 1,
    source: 'AI Generated',
    curriculum: 'MATATAG',
    outputFormat: 'Table',
    saved_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    lessonPlanTable: '<table border="1" cellspacing="0" cellpadding="10" style="width:100%;border-collapse:collapse;margin-bottom:20px;"><tr><th colspan="3">I. Objectives</th></tr><tr><td colspan="3">Cognitive: To be generated by AI based on Planets in Science.<br/>Psychomotor: To be generated by AI based on Planets in Science.<br/>Affective: To be generated by AI based on Planets in Science.</td></tr></table>'
  },
  {
    id: 'sample-2',
    subject: 'Mathematics',
    topic: 'Addition and Subtraction',
    gradeLevel: 'Grade 1',
    grade: 1,
    duration: 50,
    quarter: 2,
    source: 'AI Generated',
    curriculum: 'MATATAG',
    outputFormat: 'Table',
    saved_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    lessonPlanTable: '<table border="1" cellspacing="0" cellpadding="10" style="width:100%;border-collapse:collapse;margin-bottom:20px;"><tr><th colspan="3">I. Objectives</th></tr><tr><td colspan="3">Cognitive: Students will be able to perform basic addition and subtraction within 10.<br/>Psychomotor: Students will solve addition and subtraction problems using manipulatives.<br/>Affective: Students will appreciate the importance of numbers in daily life.</td></tr></table>'
  },
  {
    id: 'sample-3',
    subject: 'English',
    topic: 'Parts of Speech - Nouns',
    gradeLevel: 'Grade 3',
    grade: 3,
    duration: 60,
    quarter: 3,
    source: 'AI Generated',
    curriculum: 'MATATAG',
    outputFormat: 'Table',
    saved_at: new Date(Date.now() - 86400000 * 14).toISOString(),
    lessonPlanTable: '<table border="1" cellspacing="0" cellpadding="10" style="width:100%;border-collapse:collapse;margin-bottom:20px;"><tr><th colspan="3">I. Objectives</th></tr><tr><td colspan="3">Cognitive: Students will identify and classify different types of nouns.<br/>Psychomotor: Students will write sentences using appropriate nouns.<br/>Affective: Students will express appreciation for language structure.</td></tr></table>'
  }
]

const initializeHistory = () => {
  const existing = sessionStorage.getItem('lumina_history')
  if (!existing) {
    sessionStorage.setItem('lumina_history', JSON.stringify(SAMPLE_LESSONS))
    return true
  }
  return false
}

export const ensureHistory = () => {
  initializeHistory()
}

export const saveToSession = (plan) => {
  initializeHistory() // Ensure we have history
  const existing = JSON.parse(sessionStorage.getItem('lumina_history') || '[]')
  const newPlan = {
    ...plan,
    id: `lesson-${Date.now()}`,
    saved_at: new Date().toISOString(),
  }
  existing.unshift(newPlan)
  sessionStorage.setItem('lumina_history', JSON.stringify(existing))
}

export const getFromSession = () => {
  initializeHistory() // Ensure we have history
  return JSON.parse(sessionStorage.getItem('lumina_history') || '[]')
}

export const deleteFromSession = (id) => {
  const existing = getFromSession()
  const updated = existing.filter(p => p.id !== id)
  sessionStorage.setItem('lumina_history', JSON.stringify(updated))
}
